# Generated by Django 4.1.6 on 2023-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=8, verbose_name='uuid')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('body', models.TextField(max_length=2000, verbose_name='Текст')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
